server:
  port: 8080
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.215:3306/sndo?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#mybatis-config
mybatis:
  type-aliases-package: com.lumia.web.entity
debug: true

# 清除启动时提示日志
logging:
  level:
    org.spring.framework.boot.autoconfigure: error
